### PR TITLE
Update microshift-documentation repo to reflect the current upstream status and productization effort

### PR DESCRIPTION
**Pull request by ggiguash**
Update microshift-documentation repo to reflect the current upstream status and productization effort
- Replaced "CentOS 8 Stream" by "CentOS Stream"
- Updated cri-o installation instructions on "CentOS Stream" based on https://github.com/redhat-et/microshift-documentation/pull/174 PR
- Removed AIO-container instructions
- Using 4.8.0-microshift-2022-04-20-141053 branch name when cloning the repository

Closes: [USHIFT-7](https://issues.redhat.com/browse/USHIFT-7)

### CODE REVIEW

**Review by fzdarsky — COMMENTED** [review]
I'd suggest removing https://github.com/redhat-et/microshift-documentation/blob/d8f3a3330229c52b7c5328bfa6d43001777ee2a8/content/en/docs/getting-started/_index.md?plain=1#L238-L256 while we're at it.
This is only needed for developers of MicroShift not users and has lead to confusion with people in the past.

**Comment by ggiguash** [comment]
Removed the requested section

**Comment by fzdarsky** [comment]
Thanks.
/LGTM

**Pull request merged**
