### PR TITLE
Update to `docsy` theme, forked from k8s docs, and update file structure

### PR DESCRIPTION
**Pull request by sallyom**
updates from community mtg and design doc

What will publish if merged as/is: [See screenshots here](https://github.com/redhat-et/microshift-documentation/pull/59#issuecomment-977815102)

TODO (can be done after merge):
- add back/check if compatible [the tabs PR](https://github.com/redhat-et/microshift-documentation/commit/5e3270a719be26200403442b442049e07e48f431) (@mangelajo)
- The admonitions (warning, note)  from @iranzo I think are nicer, update back to those 
- update to a new `texture.png` for the header/footer background, since this is same as k8s
- update Makefile & for local builds ensure nodejs is installed and run `npm install` before building 

@cooktheryan @fzdarsky @husky-parul

### CODE REVIEW

**Comment by sallyom** [comment]
Screenshot from 2021-11-19 01-03-27

**Comment by sallyom** [comment]
(bonus) I added a watch button and a page to display the end-to-end video (and/or any future demo videos can be added)
Screenshot from 2021-11-19 01-08-27

**Comment by mangelajo** [comment]
I like this theme more, more readable, easier to follow, I feel we should build on this, but let's hear @fzdarsky , etc

btw, in my case something fails with the docs page: 
image

**Comment by mangelajo** [comment]
This can be helpful for review:

```
git diff origin/main -- . :^theme :^assets :^*.svg 
```

**Comment by sallyom** [comment]
@mangelajo looking at that now, hm.
Also, I'm going to do a proper fork of k8s/website rather than a cp/paste, I think I can make that happen, let's see...

**Comment by sallyom** [comment]
> I like this theme more, more readable, easier to follow, I feel we should build on this, but let's hear @fzdarsky , etc
> 
> btw, in my case something fails with the docs page: image

please check again, I hope it is resolved, thank you

**Comment by sallyom** [comment]
updated the color scheme:
Screenshot from 2021-11-22 01-08-55

**Comment by sallyom** [comment]
other page
Screenshot from 2021-11-22 08-22-09

**Comment by mangelajo** [comment]
Nueva nota
Nueva nota


There's something odd/wrong here. (safari?)

**Comment by sallyom** [comment]
@mangelajo I found the problem, the `static` dir was listed in .gitignore, so only I had all the static (and themes.../static) files, they didn't get pushed. 
Here's what it should look like now:
Screenshot from 2021-11-22 14-47-35

**Comment by mangelajo** [comment]
it works great now. Our builder doesn't work anymore though ^ see CI. May be we should start using make server / make static ? 

And also have something on the make to ensure npm install has ben ran? (just ideas) ;)

**Comment by sallyom** [comment]
> it works great now. Our builder doesn't work anymore though ^ see CI. May be we should start using make server / make static ?
> 
> And also have something on the make to ensure npm install has ben ran? (just ideas) ;)

Definitely, after the holiday will do that - the published docs are in rough shape-I'd like to get this merged, wdyt? 
@cooktheryan CI builder will need `nodejs` and also run this, I hope that's all: `sudo npm install`

**Comment by sallyom** [comment]
PR as/is:
documentation:
Screenshot from 2021-11-24 07-00-10
landing page:
Screenshot from 2021-11-24 06-59-59
footer:
Screenshot from 2021-11-24 07-00-17

**Comment by mangelajo** [comment]
it looks good to me!, I can re-add what's missing for the tabs.

**Review by mangelajo — APPROVED** [review]
/lgtm

**Pull request merged**
